
DEV_ADC_FILEPATH = '/dev/iio:device0'
BUF_SIZE_SAMPLES = 768 #best depends on sample rate and process+image gen latency. ~768 for 30ms/buf
BYTES_PER_SAMPLE = 2 #uint16 containers
CHUNK_SIZE_BYTES = BUF_SIZE_SAMPLES * BYTES_PER_SAMPLE
PROCESSING_CHUNK_SIZE = 1024
SAMPLERATE = 20000 
FLUSH_ITER = 0
FLUSH_BUF_SIZE = 256

MAT_SIZE_W = 64
MAT_SIZE_H = 32
MAT_NUM_CHANNEL = 3
BIN_PIXEL_WIDTH = 1

FREQ_MIN=18 #Hz, lower than 20 to capture 19. and such
FREQ_MAX= SAMPLERATE / 2

NUM_OUTPUT_BINS = int(MAT_SIZE_W / BIN_PIXEL_WIDTH)
MIN_MAX_DB = 60 # 70 is a good value

MAX_UINT8 = 255
IMAGE_MAX_VAL = 255
IMAGE_NORM_FACTOR = MAX_UINT8 / IMAGE_MAX_VAL