
DEV_ADC_FILEPATH = '/dev/iio:device0'
BUF_SIZE = 2048
ELEMENT_SIZE = 2 #uint16 containers
CHUNK_SIZE = BUF_SIZE * ELEMENT_SIZE
SAMPLERATE = 40000 

MAT_SIZE_W = 64
MAT_SIZE_H = 32
BIN_PIXEL_WIDTH = 2

NUM_OUTPUT_BINS = int(MAT_SIZE_W / BIN_PIXEL_WIDTH)